# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107293164b92646215bd6be8747a14f3973ffda019a025dad2d723fe71bee0114c9c21f31a2fbee68130a30654b4207dacacb7c3762e31a5131822f20c55a0db

test:
  secret_key_base: 34a27b6399e8a35a108d53fb80594408c46af30fd4e8ad15ae1cdbb01fcb0e83d31a5aed29349747f805819e6deccb4e476e5b8951079dc9a88d9eebb78614a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
